### ISSUE TITLE
Panic during execution

### ISSUE THREAD

**Issue by PatWie** [drone-plugins/drone-github-release#31]
Very nice project!

However, I am struggeling with this plugin. In my `.drone.yml` file I wrote

```yaml
  publish:
    image: plugins/drone-github-release
    secrets: [ github_token ]
    files:
      - saccade_release.tar.gz
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
```

All pipeline steps are working up to deploy. I get

```
Drone GitHub Release Plugin built from 3375ca6
panic: EOF
goroutine 1 [running]:
panic(0x79a7e0, 0xc82000a0f0)
/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/drone-plugins/drone-github-release/vendor/github.com/drone/drone-go/plugin.MustParse()
/drone/src/github.com/drone-plugins/drone-github-release/vendor/github.com/drone/drone-go/plugin/plugin.go:132 +0x59
main.main()
/drone/src/github.com/drone-plugins/drone-github-release/main.go:33 +0x5ae
```

Unfortunately, I do not know how to debug this behavior.  The entire project is [open-source on github](https://github.com/PatWie/saccade/tree/deploy) and I pushed the docker images to docker-hub (the drone.yml refers to these public images). SO it should reproducible, see:

https://ci.patwie.com/PatWie/saccade/33
