### ISSUE TITLE
Prerelease flag issue

### ISSUE THREAD

**Issue by vishal24tuniki** [drone-plugins/drone-github-release#32]
Hi I am writing this to discuss if there is any better way to handle the prerelease flag?
People generally create releases on master and prereleases on other branches. With the current implementation of plugin, it constantly requires users to modify .drone.yml from branch to branch with an apt value for prerelease flag, so a release of desired state (prerelease or normal release) is created when they create a git tag.
I can think of 2 solutions to tackle this problem

1. Have a regex field which decides the release is prerelease or normal release (lets say if a tag contains characters `rc`, then the release that gets created is prerelease, else it is a normal release)
2. Ask users to create an annotated tag, which contains string "prerelease" by which the plugin can create a pre-release, in all other cases it can create a normal release.

Do let me know your opinion. In case of any contribution required, i can do the changes if it seems right

**Comment by bkcsoft** [comment]
https://github.com/go-gitea/gitea has a similar problem, where we create prereleases based on the tag-name. I haven't found a way to have drone run different builds based on tag-names either, would really like to be able to do `prerelease_reges: ".*-rc.+"` or similar.

**Comment by vishal24tuniki** [comment]
@tboerger @bradrydzewski can you please help

**Comment by appleboy** [comment]
try the following:

```
  github:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - dist/release/*
    when:
      event: [ tag ]
      branch: [ refs/tags/rc* ]
```

**Comment by tboerger** [comment]
Like @appleboy suggested you should add the plugin twice with different conditions, than it just works like it is and you can use the globbing provided by the drone conditions.

**Comment by vishal24tuniki** [comment]
@appleboy @tboerger can the regex be something like this?
`branch: [ refs/tags/*rc* ]`

**Comment by appleboy** [comment]
@vishal24tuniki Yes.

**Comment by vishal24tuniki** [comment]
Thank you. It seems fine. But does the regex support not conditions?
Because when the tag doesn't contain "rc", i would like i to be
prerelease:false

**Comment by vishal24tuniki** [comment]
Just remembered it can be achieved through `include` and `exclude` conditions present for filtering branches

**Comment by vishal24tuniki** [comment]
```
  xxx_prerelease:
    image: plugins/github-release
    prerelease: true
    files:
        - release/linux/amd64/binary
    secrets: [ github_token ]
    when:
      event: tag
      branch:
          include: [ refs/tags/*rc*, refs/tags/*alpha*, refs/tags/*beta* ]
      status: success

  xxx_release:
    image: plugins/github-release
    files:
        - release/linux/amd64/binary
    secrets: [ github_token ]
    when:
      event: tag
      branch:
          exclude: [ refs/tags/*rc*, refs/tags/*alpha*, refs/tags/*beta* ]
      status: success
```
