### ISSUE TITLE
Checksum files contain the full file path

### ISSUE THREAD

**Issue by allanrenucci** [drone-plugins/drone-github-release#33]
Hi,

When generating the checksum file, it would be nice to have an option to specify if we want the generated file to contain full paths or only file names. For example:
```yml
files:
  - a/b/c
checksum:
  - sha256
```
generates
```
123 a/b/c
```
and I'd like
```
123 c
```
