### ISSUE TITLE
Publish a drafted release

### ISSUE THREAD

**Issue by iwilltry42** [drone-plugins/drone-github-release#65]
First off: Thanks for this awesome Drone Plugin :)

I have the following config for pre-releases (and similar for releases)
```yaml
- name: pre-release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - _dist/*
    checksum:
      - sha256
    prerelease: true
  depends_on:
    - lint
    - test
    - build
  when:
    event:
      - tag
    ref:
      include:
        - "refs/tags/*rc*"
        - "refs/tags/*beta*"
        - "refs/tags/*alpha*"
```
In general, this works really well.
However, I'd like to achieve the following flow, which I'm used to from TravisCI:

1. I draft a release for tag vX.Y.Z
2. I trigger the drone pipeline by pushing tag vX.Y.Z
3. Drone builds the release files, picks up the draft release, updates it with the new details and publishes it

So in basic steps: Manually draft a Release -> Drone updates and publishes this release

Right now, Drone will just create a new release with the same tag, rendering the draft invalid.
