### ISSUE TITLE
The plugin failed silently with the latest docker image

### ISSUE THREAD

**Issue by HugoPoi** [drone-plugins/drone-github-release#66]
Before the release publish on the docker hub `6/16/2020 at 6:36 pm` hash `fa70c21cc997880d9d43a7bbcc6cfc580b612b6e5186bc9d84c29e3663da29b1` it was working. Now my publish task fail silently with no error message.

```
latest: Pulling from plugins/github-release
Digest: sha256:fa70c21cc997880d9d43a7bbcc6cfc580b612b6e5186bc9d84c29e3663da29b1
Status: Image is up to date for plugins/github-release:latest
```
Sample config
```yaml
- name: publish
  image: plugins/github-release
  volumes:
  - name: output
    path: /drone/src/output
  settings:
    api_key:
      from_secret: GITHUB_API_KEY
    files:
      - output/images/*.img.gz
    checksum:
      - sha256
    draft: true
    prerelease: true
  when:
    event: tag
```

Take a look => https://arm-build.yunohost.org/YunoHost/arm-images/22/1/10

Working with the version tagged `plugins/github-release:1` and the an other one with hash `204e1fbad9d543890e7ed7c28d20dfc1cab659df88c659dda5add5208fa74f4d` ( gone because not tagged )
