### ISSUE TITLE
Plugin failure

### ISSUE THREAD

**Issue by Upgreydd** [drone-plugins/drone-github-release#71]
```
latest: Pulling from plugins/github-release
--
2 | Digest: sha256:d7b0d14cd45b9bcc370810fda6b52ff3cc2aada5ede62e6f3005c3d8670f4510
3 | Status: Downloaded newer image for plugins/github-release:latest
4 | no existing release (draft) found for the given tag
5 | panic: runtime error: invalid memory address or nil pointer dereference
6 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x80f256]
7 |  
8 | goroutine 1 [running]:
9 | github.com/drone-plugins/drone-github-release/plugin.(*Plugin).Execute(0xc000130b00, 0x0, 0x0)
10 | /drone/src/plugin/impl.go:147 +0x386
11 | main.run.func1(0xc000033a80, 0xc00000eb00, 0x50)
12 | /drone/src/cmd/drone-github-release/main.go:60 +0x386
13 | github.com/urfave/cli/v2.(*App).RunContext(0xc000001200, 0x9fb1a0, 0xc00002a038, 0xc0000201e0, 0x1, 0x1, 0x0, 0x0)
14 | /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:315 +0x70b
15 | github.com/urfave/cli/v2.(*App).Run(...)
16 | /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
17 | main.main()
18 | /drone/src/cmd/drone-github-release/main.go:37 +0x223

```
Caused by task:
```
- name: Create release in GitHub
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
  when:
    event: tag
```
Should create release without attaching files.
